package net.davio.aquaticambitions.registry;

import net.davio.aquaticambitions.CreateAquaticAmbitions;
import net.davio.aquaticambitions.content.processing.conduit.MechanicalConduitEffectDefinition;
import net.minecraft.core.Registry;
import net.minecraft.resources.ResourceKey;

/**
 * Keys for datapack registries added by this mod. These are registered at runtime via
 * {@code DataPackRegistryEvent.NewRegistry} (see {@code CAACommonEvents}) and their built-in default
 * entries are generated by {@code CAAConduitEffectsProvider}.
 */
public class CAARegistries {
    public static final ResourceKey<Registry<MechanicalConduitEffectDefinition>> CONDUIT_EFFECT = key("conduit_effect");

    private static <T> ResourceKey<Registry<T>> key(String name) {
        return ResourceKey.createRegistryKey(CreateAquaticAmbitions.asResource(name));
    }

    private CAARegistries() {
    }
}
