modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
logoFile="icon.png"

[[mods]] #mandatory
    modId="create_aquatic_ambitions" #mandatory
    version="${mod_version}" #mandatory
    displayName="${mod_name}" #mandatory
    authors="${mod_authors}"
    description='''
    ${mod_description}
    '''
#Dependencies
[[dependencies.create_aquatic_ambitions]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.create_aquatic_ambitions]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_aquatic_ambitions]]
    modId="create"
    mandatory=true
    versionRange="[6.0.6,)"
    ordering="NONE"
    side="BOTH"

