modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/davioliva16/create-aquatic-ambitions/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"

#logoFile="caa.png"
#credits=""

authors="${mod_authors}"

description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="[${minecraft_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="create"
    type="required"
    versionRange="[6.0.8,6.1.0)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="kubejs"
    type="optional"
    versionRange="${kubejs_version_range}"
    ordering="NONE"

[[dependencies.${mod_id}]]
    modId="jei"
    type="optional"
    versionRange="${jei_version_range}"
    ordering="NONE"
